### ISSUE TITLE
Issues and Bugs

### ISSUE THREAD

**Issue by svenkeidel** [svenkeidel/hug#3]
Hi,

I recently added HSpec tests to the shoebox app. @vajkonny, you added a todo file with a few issues and bugs. Could you write a failing test that exercises the wrong or missing behavior of the code? Then we can fix the issue in the next meetup together and see if the test turns green.

You can run and execute the tests with the following commands:

``` shell
cd ./shoebox
# This is only necessary if you haven't installed HSpec yet.
# cabal install --dependencies-only --enable-tests
cabal configure --enable-tests
cabal build
./dist/build/specs/specs
```

Let me know how it goes.

Best,
Sven

**Comment by vajkonny** [comment]
Hi Sven,

Am 26.09.2015 11:59, schrieb Sven Keidel:

> @vajkonny https://github.com/vajkonny, you added a todo file with a 
> few issues and bugs. Could you write a failing test that exercises the 
> wrong or missing behavior of the code? Then we can fix the issue in 
> the next meetup together and see if the test turns green. 

Du meinst sicher die Punkte 0. und 1. in der Liste, bzw. evtl noch Punkt 
4. und den in der hochgeladenen Version noch nicht enthaltenen Punkt 8. 
Alles andere sind ja eher konzeptionelle Vorschläge, über deren 
Umsetzung wir uns noch einigen müssen.

zu #0: Hier bin ich mir unsicher, ob [ILB [TX "maisons", (MB 
[MorphemeLex "maison",MorphemeSuffix "s"]), (GL [Meaning 
"house",Abbreviation "PL"])]] wirklich die gewünschte Ausgabe sein soll. 
Was meinst Du dazu? Habe ich Dich da überhaupt im Prinzip richtig 
verstanden?

zu #1, #4, #8 und Teile von #6: Hier könnte ich mich dran versuchen, 
aber meine Haskell-Kenntnisse sind halt sehr begrenzt. Ausserdem bin ich 
nicht sicher, ob wir "Hausaufgaben" zwischen den Treffen vergeben 
sollten, oder ob wir das erstmal jeweils gemeinsam machen sollen. Wenn 
sich noch mehr Leute im github anmelden, wäre das okay.

Der noch zu ergänzende #8 in der Todolist ist übrigens:
8. strip off punctuation:

import qualified Data.Set as S
punctuation = S.fromList ",?,-;'\""
removePunc = filter (`S.notMember` punctuation)

(should be refined so that punctuation is only being removed in front or 
after whitespace!)

zu  HSPEC: ich habe leider gar keine Ahnung davon, wie man Tests 
schreibt. Schon gar nicht in Haskell. Ich müsste mich wirklich endlich 
mal da hineinarbeiten, aber dazu fehlt mir gerade die Zeit. Ich weiss, 
dass das sehr wichtig ist... Oder hast Du ein ganz einfaches 
Hello-World-Beispiel parat?

Schreib mir gerne mal, ob die todolist so verständlich ist. Im Moment 
ist sie erst einmal eine Gedankenstütze für mich selbst, die ich schon 
mal mit Euch geteilt habe.

Herzlich,
Harald

## 

"If you have a choice of two things and can't decide, take both." -- Gregory Corso

**Comment by vajkonny** [comment]
Am 26.09.2015 15:17, schrieb Harald Vajkonny:

> zu  HSPEC: ich habe leider gar keine Ahnung davon, wie man Tests 
> schreibt. Schon gar nicht in Haskell. Ich müsste mich wirklich endlich 
> mal da hineinarbeiten, aber dazu fehlt mir gerade die Zeit. Ich weiss, 
> dass das sehr wichtig ist... Oder hast Du ein ganz einfaches 
> Hello-World-Beispiel parat?
> Habs mir gerade angesehen. Ist ja ganz easy. Damit komme ich klar.

Harald

## 

"If you have a choice of two things and can't decide, take both." -- Gregory Corso

**Comment by svenkeidel** [comment]
Die TODO Liste ist verständlich :+1: . Danke für die Tests.
